
pool:
  vmImage: ubuntu-latest

trigger:
  - main
  - feature/*
  - release/*
pr:
  - main
  - feature/*
  - release/*

steps:
  - checkout: self
    fetchDepth: 0

  - script: |
      echo "##vso[task.setvariable variable=version;]$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
    displayName: Build configuration

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'atg'
      mavenServiceConnections: 'mavenfeed'

  - task: Maven@3
    displayName: Build
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      goals: 'clean verify'

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'atg'
      mavenServiceConnections: 'mavenfeed'

  - task: Maven@3
    displayName: Deploy Artifacts
    condition: eq(startsWith(variables['Build.SourceBranch'], 'refs/heads/main'),'True')
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      jdkArchitectureOption: 'x64'
      mavenAuthenticateFeed: true
      publishJUnitResults: false
      goals: 'jar:jar deploy:deploy'
